import os
import sys
import subprocess
import shutil
import time
from typing import Dict, Any, List

def execute_code(code_str: str, data_file_path: str, output_dir: str, timeout: int = 30) -> Dict[str, Any]:
    """
    Executes Python/Pandas code in a separate subprocess.
    Isolates the run by copying the input data file into a clean workspace,
    running the code, and identifying created files.
    """
    # 1. Create a clean run workspace inside output_dir
    run_id = f"run_{int(time.time() * 1000)}"
    sandbox_dir = os.path.join(output_dir, run_id)
    os.makedirs(sandbox_dir, exist_ok=True)

    # 2. Copy the data file into the sandbox directory so the script can load it locally
    data_filename = os.path.basename(data_file_path)
    sandbox_data_path = os.path.join(sandbox_dir, data_filename)
    shutil.copy2(data_file_path, sandbox_data_path)

    # 3. Create the Python script
    script_path = os.path.join(sandbox_dir, "analyse.py")
    
    # We replace any reference to the full data path with the local filename,
    # so the agent doesn't get confused about paths.
    # We also set MPLBACKEND=Agg to prevent matplotlib GUI rendering issues.
    local_code = code_str
    # If the code tries to load the absolute path, make sure it maps to the local copied version
    # Actually, the agent will be instructed to load 'data_filename' directly, but we can make it robust:
    local_code = local_code.replace(data_file_path, data_filename)
    
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(local_code)

    # 4. Execute the script in a subprocess
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"  # Run matplotlib in headless mode
    
    # We run using the same python interpreter
    python_exe = sys.executable

    start_time = time.time()
    try:
        process = subprocess.run(
            [python_exe, "analyse.py"],
            cwd=sandbox_dir,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout
        )
        execution_time = time.time() - start_time
        stdout = process.stdout
        stderr = process.stderr
        exit_code = process.returncode
        success = (exit_code == 0)
    except subprocess.TimeoutExpired as e:
        execution_time = time.time() - start_time
        stdout = e.stdout or ""
        stderr = f"Execution timed out after {timeout} seconds."
        exit_code = -1
        success = False
    except Exception as e:
        execution_time = time.time() - start_time
        stdout = ""
        stderr = f"Failed to launch process: {str(e)}"
        exit_code = -1
        success = False

    # 5. Scan for files generated by the execution (excluding the script and data itself)
    ignored_files = {"analyse.py", data_filename}
    generated_files = []
    
    if os.path.exists(sandbox_dir):
        for f in os.listdir(sandbox_dir):
            if f not in ignored_files:
                file_path = os.path.join(sandbox_dir, f)
                # Keep it relative to sandbox_dir or copy back?
                # We can store them in the sandbox directory and return their absolute paths.
                generated_files.append(file_path)

    return {
        "success": success,
        "exit_code": exit_code,
        "stdout": stdout,
        "stderr": stderr,
        "execution_time": execution_time,
        "generated_files": generated_files,
        "sandbox_dir": sandbox_dir,
        "local_data_path": sandbox_data_path
    }

# Small test block
if __name__ == "__main__":
    # Create test code that makes a plot
    test_code = """
import pandas as pd
import matplotlib.pyplot as plt

# Load the local data
df = pd.read_csv('test.csv')
print("Shape:", df.shape)

# Create and save a plot
plt.figure()
df.plot(kind='bar', x='Name', y='Score')
plt.title('Scores')
plt.savefig('output_plot.png')
plt.close()

# Save summary
df.describe().to_csv('summary.csv')
print("Finished analysis successfully!")
"""
    # Create a dummy CSV
    os.makedirs("./temp_test", exist_ok=True)
    with open("./temp_test/test.csv", "w") as f:
        f.write("Name,Score\nAlice,90\nBob,85\nCharlie,95")

    result = execute_code(test_code, "./temp_test/test.csv", "./temp_test")
    print("Success:", result["success"])
    print("Stdout:", result["stdout"].strip())
    print("Stderr:", result["stderr"].strip())
    print("Files created:", [os.path.basename(f) for f in result["generated_files"]])
    
    # Cleanup temp
    shutil.rmtree("./temp_test", ignore_errors=True)
